# Generated by Django 6.0.1 on 2026-01-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_category_user_transaction_user_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="category",
            name="uniq_global_category_name",
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=80),
        ),
    ]
